import os
import re
import time
import requests

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "").strip()

# Use stable free endpoints first, then the OpenRouter free router as a final fallback.
# These are current free model IDs available on OpenRouter.
MODELS = [
    "google/gemma-4-31b-it:free",
    "qwen/qwen3-30b-a3b:free",
    "nvidia/nemotron-3-super-120b-a12b:free",
    "openrouter/free",
]

MIN_CHARS = 4500
TARGET_MIN_CHARS = 5000
TARGET_MAX_CHARS = 5500
MAX_CHARS = 5700

MAX_ATTEMPTS = 6

SCRIPTS_DIR = BASE_DIR / "scripts"


def remove_urls(text):
    text = re.sub(
        r"https?://\S+",
        "",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"www\.\S+",
        "",
        text,
        flags=re.IGNORECASE,
    )

    return text


def remove_coordinates(text):
    patterns = [
        r"\b\d{1,3}\s*°\s*\d{1,2}\s*[′']?\s*\d{0,2}(?:\.\d+)?\s*[″\"]?\s*[NS]\b",
        r"\b\d{1,3}\s*°\s*\d{1,2}\s*[′']?\s*\d{0,2}(?:\.\d+)?\s*[″\"]?\s*[EW]\b",
        r"\b\d{1,3}(?:\.\d+)?\s*[NS]\b",
        r"\b\d{1,3}(?:\.\d+)?\s*[EW]\b",
        r"\b(?:latitude|longitude)\s*[:\-]?\s*\d+(?:\.\d+)?\b",
        r"\b(?:lat|lon|lng)\s*[:\-]?\s*\d+(?:\.\d+)?\b",
        r"\b\d+(?:\.\d+)?\s*,\s*\d+(?:\.\d+)?\b",
    ]

    for pattern in patterns:
        text = re.sub(
            pattern,
            " ",
            text,
            flags=re.IGNORECASE,
        )

    return text


def remove_forbidden_measurements(text):
    def miles_to_km(match):
        value = float(match.group(1))
        km = value * 1.60934

        if km >= 100:
            return f"{round(km)} kilometres"

        return f"{round(km, 1)} kilometres"

    def feet_to_m(match):
        value = float(match.group(1))
        metres = value * 0.3048

        if metres >= 100:
            return f"{round(metres)} metres"

        return f"{round(metres, 1)} metres"

    def fahrenheit_to_celsius(match):
        value = float(match.group(1))
        celsius = (value - 32) * 5 / 9

        return f"{round(celsius, 1)} degrees Celsius"

    text = re.sub(
        r"(\d+(?:\.\d+)?)\s*(?:miles|mile|mi)\b",
        miles_to_km,
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"(\d+(?:\.\d+)?)\s*(?:feet|foot|ft)\b",
        feet_to_m,
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"(\d+(?:\.\d+)?)\s*(?:°F|degrees?\s+Fahrenheit)\b",
        fahrenheit_to_celsius,
        text,
        flags=re.IGNORECASE,
    )

    return text


def clean_text(text):
    text = remove_urls(text)
    text = remove_coordinates(text)
    text = remove_forbidden_measurements(text)

    text = re.sub(
        r"\b(?:latitude|longitude|coordinates?|gps coordinates?)\b",
        "",
        text,
        flags=re.IGNORECASE,
    )

    text = text.replace("\r", " ")
    text = text.replace("\n", " ")

    text = re.sub(
        r"\s+",
        " ",
        text,
    )

    return text.strip()


def split_sentences(text):
    text = text.strip()

    if not text:
        return []

    parts = re.split(
        r"(?<=[.!?।])\s+",
        text,
    )

    return [
        part.strip()
        for part in parts
        if part.strip()
    ]


def normalize_sentence(sentence):
    sentence = sentence.strip()

    sentence = re.sub(
        r"\s+",
        " ",
        sentence,
    )

    return sentence


def sentence_key(sentence):
    sentence = sentence.lower()

    sentence = re.sub(
        r"[^a-z0-9\u0C00-\u0C7F]+",
        " ",
        sentence,
    )

    sentence = re.sub(
        r"\s+",
        " ",
        sentence,
    )

    return sentence.strip()


def repetition_ratio(text):
    sentences = split_sentences(text)

    if len(sentences) < 5:
        return 0.0

    keys = [
        sentence_key(sentence)
        for sentence in sentences
    ]

    keys = [
        key
        for key in keys
        if len(key) > 15
    ]

    if not keys:
        return 0.0

    unique_count = len(set(keys))

    return 1 - (
        unique_count / len(keys)
    )


def contains_meta_text(text):
    lowered = text.lower()

    forbidden = [
        "as an ai",
        "as a language model",
        "ai generated",
        "generated by ai",
        "scriptwriter",
        "script writer",
        "here is the script",
        "here's the script",
        "in this script",
        "according to the prompt",
        "prompt",
        "instructions",
        "word count",
        "character count",
        "sources:",
        "references:",
        "youtube description",
        "thumbnail",
    ]

    return any(
        phrase in lowered
        for phrase in forbidden
    )


def contains_forbidden_content(text):
    lowered = text.lower()

    forbidden_patterns = [
        r"https?://",
        r"www\.",
        r"\b\d+(?:\.\d+)?\s*(?:miles?|mi)\b",
        r"\b\d+(?:\.\d+)?\s*(?:feet|foot|ft)\b",
        r"\blatitude\b",
        r"\blongitude\b",
        r"\bcoordinates?\b",
        r"\bgps coordinates?\b",
        r"\b\d{1,3}\s*°\s*\d{1,3}",
    ]

    for pattern in forbidden_patterns:
        if re.search(
            pattern,
            lowered,
            flags=re.IGNORECASE,
        ):
            return True

    return False


def sanitize_final_script(text):
    text = clean_text(text)

    sentences = split_sentences(text)

    cleaned_sentences = []
    seen = set()

    for sentence in sentences:
        sentence = normalize_sentence(sentence)

        if not sentence:
            continue

        key = sentence_key(sentence)

        if not key:
            continue

        if key in seen:
            continue

        seen.add(key)
        cleaned_sentences.append(sentence)

    text = " ".join(
        cleaned_sentences
    )

    text = clean_text(text)

    return text.strip()


def trim_to_target(text, max_chars=TARGET_MAX_CHARS):
    if len(text) <= max_chars:
        return text

    sentences = split_sentences(text)

    result = []
    current_length = 0

    for sentence in sentences:
        sentence = sentence.strip()

        if not sentence:
            continue

        extra_length = len(sentence)

        if result:
            extra_length += 1

        if (
            current_length + extra_length
            > max_chars
        ):
            break

        result.append(sentence)
        current_length += extra_length

    trimmed = " ".join(result).strip()

    if len(trimmed) >= MIN_CHARS:
        return trimmed

    fallback = text[:max_chars]

    fallback = fallback.rsplit(
        " ",
        1,
    )[0].strip()

    return fallback


def validate_script(text):
    if not text:
        return False, "EMPTY SCRIPT"

    length = len(text)

    if length < MIN_CHARS:
        return False, (
            f"TOO SHORT: {length} characters"
        )

    if length > MAX_CHARS:
        return False, (
            f"TOO LONG: {length} characters"
        )

    if contains_meta_text(text):
        return False, "META TEXT DETECTED"

    if contains_forbidden_content(text):
        return False, "FORBIDDEN CONTENT DETECTED"

    ratio = repetition_ratio(text)

    if ratio > 0.30:
        return False, (
            f"TOO REPETITIVE: {ratio:.2f}"
        )

    sentences = split_sentences(text)

    if len(sentences) < 25:
        return False, (
            f"TOO FEW SENTENCES: {len(sentences)}"
        )

    return True, "VALID"


def build_prompt(topic_id, title, research):
    return f"""
నువ్వు తెలుగు యూట్యూబ్ డాక్యుమెంటరీ స్క్రిప్ట్ రైటర్.

టాపిక్:
{title}

టాపిక్ ID:
{topic_id}

కింద ఇచ్చిన పరిశోధన సమాచారాన్ని మాత్రమే ఆధారంగా చేసుకుని సహజమైన తెలుగు డాక్యుమెంటరీ narration రాయాలి.

RESEARCH:
{research}

కఠినమైన నియమాలు:

1. స్క్రిప్ట్ మొత్తం సహజంగా మాట్లాడే తెలుగు narration లాగా ఉండాలి.
2. మొత్తం 5000 నుంచి 5500 characters మధ్య ఉండాలి.
3. 7 నుంచి 8 నిమిషాల voice-over కి సరిపోయేలా ఉండాలి.
4. ప్రారంభం ఆసక్తికరంగా ఉండాలి.
5. విషయం క్రమంగా explain చేయాలి.
6. చివర్లో సహజమైన ముగింపు ఉండాలి.
7. అకస్మాత్తుగా narration ఆపకూడదు.
8. Headings పెట్టకూడదు.
9. Bullet points పెట్టకూడదు.
10. Numbered lists పెట్టకూడదు.
11. Introduction, Conclusion వంటి headings వద్దు.
12. URLs ఇవ్వకూడదు.
13. Sources లేదా references list ఇవ్వకూడదు.
14. AI గురించి చెప్పకూడదు.
15. Coordinates వద్దు.
16. Latitude లేదా longitude గురించి చెప్పకూడదు.
17. GPS coordinates గురించి చెప్పకూడదు.
18. Miles, mile, mi వాడకూడదు.
19. Feet, foot, ft వాడకూడదు.
20. దూరాలకు kilometres లేదా km మాత్రమే వాడాలి.
21. ఎత్తు లేదా లోతుకు metres లేదా m మాత్రమే వాడాలి.
22. అవసరం లేని decimals వాడకూడదు.
23. Research లో లేని facts కల్పించకూడదు.
24. ఒకే విషయాన్ని మళ్లీ మళ్లీ చెప్పకూడదు.
25. ఒకే sentence లేదా idea repeated wording తో చెప్పకూడదు.
26. Myth మరియు fact మధ్య స్పష్టమైన తేడా ఉండాలి.
27. నిర్ధారించని విషయాలను నిజాలుగా చెప్పకూడదు.
28. సహజమైన conversational Telugu వాడాలి.
29. English words చాలా అవసరమైనప్పుడు మాత్రమే ఉపయోగించాలి.
30. చివరి paragraph పూర్తి sentence తో ముగియాలి.
31. Script మాత్రమే ఇవ్వాలి.
32. Character count, word count లేదా validation గురించి చెప్పకూడదు.
33. Research లో ఉన్న facts అన్నింటినీ ఒకే paragraph లో dump చేయకుండా natural story flow లో ఉపయోగించాలి.

ముఖ్యంగా:
నిజమైన పరిశోధనలో ఉన్న సమాచారాన్ని మాత్రమే ఉపయోగించాలి.
అనుమానం ఉన్న విషయాలను fact లాగా చెప్పకూడదు.
Narration మొత్తం ఒక continuous documentary story లాగా ఉండాలి.
"""


def extract_content(data):
    choices = data.get("choices")

    if not isinstance(choices, list):
        return ""

    if not choices:
        return ""

    first_choice = choices[0]

    if not isinstance(first_choice, dict):
        return ""

    message = first_choice.get("message")

    if not isinstance(message, dict):
        return ""

    content = message.get("content")

    if isinstance(content, str):
        return content.strip()

    if isinstance(content, list):
        text_parts = []

        for item in content:
            if not isinstance(item, dict):
                continue

            item_text = item.get("text")

            if isinstance(item_text, str):
                text_parts.append(
                    item_text
                )

        return "\n".join(
            text_parts
        ).strip()

    return ""


def request_openrouter(prompt, model):
    if not OPENROUTER_API_KEY:
        raise RuntimeError(
            "OPENROUTER_API_KEY is not configured"
        )

    url = (
        "https://openrouter.ai/api/v1/"
        "chat/completions"
    )

    headers = {
        "Authorization": (
            f"Bearer {OPENROUTER_API_KEY}"
        ),
        "Content-Type": "application/json",
        "HTTP-Referer": (
            "https://github.com/"
            "gowthammedia11/telugu-mystery-ai"
        ),
        "X-Title": "Telugu Mystery AI",
    }

    payload = {
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You write factual Telugu "
                    "documentary narration. "
                    "Follow all constraints exactly. "
                    "Return only the narration."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        "temperature": 0.45,
        "max_tokens": 4000,
    }

    response = requests.post(
        url,
        headers=headers,
        json=payload,
        timeout=180,
    )

    response_text = response.text.strip()

    if response.status_code >= 400:
        raise RuntimeError(
            f"HTTP {response.status_code}: "
            f"{response_text[:500]}"
        )

    try:
        data = response.json()
    except ValueError:
        raise RuntimeError(
            "OpenRouter returned invalid JSON: "
            f"{response_text[:500]}"
        )

    content = extract_content(data)

    if content:
        return content

    # Useful diagnostic information instead of silently
    # treating every empty response as the same failure.
    error_data = data.get("error")

    if error_data:
        if isinstance(error_data, dict):
            error_message = error_data.get(
                "message",
                "Unknown OpenRouter error",
            )

            raise RuntimeError(
                f"OpenRouter error: {error_message}"
            )

        raise RuntimeError(
            f"OpenRouter error: {error_data}"
        )

    choices = data.get("choices")

    if choices:
        first_choice = choices[0]

        finish_reason = ""

        if isinstance(
            first_choice,
            dict,
        ):
            finish_reason = first_choice.get(
                "finish_reason",
                "",
            )

            message = first_choice.get(
                "message",
                {},
            )

            if isinstance(message, dict):
                reasoning = message.get(
                    "reasoning",
                    "",
                )

                if reasoning:
                    raise RuntimeError(
                        "Model returned reasoning "
                        "but no final content"
                    )

        raise RuntimeError(
            "OpenRouter returned empty content "
            f"(finish_reason={finish_reason})"
        )

    raise RuntimeError(
        "OpenRouter returned empty content"
    )


def generate_script(topic_id, title, research):
    print("=" * 70)
    print("GENERATING LONG SCRIPT")
    print("=" * 70)

    prompt = build_prompt(
        topic_id,
        title,
        research,
    )

    last_error = "Unknown error"

    for attempt in range(
        1,
        MAX_ATTEMPTS + 1,
    ):
        model = MODELS[
            (attempt - 1) % len(MODELS)
        ]

        print(
            f"OPENROUTER SCRIPT ATTEMPT "
            f"{attempt}/{MAX_ATTEMPTS}"
        )

        print(
            f"MODEL: {model}"
        )

        try:
            raw_text = request_openrouter(
                prompt,
                model,
            )

            print(
                f"RAW SCRIPT LENGTH: "
                f"{len(raw_text)}"
            )

            if not raw_text:
                last_error = (
                    "EMPTY RESPONSE"
                )

                print(
                    "SCRIPT GENERATION ERROR: "
                    f"{last_error}"
                )

                time.sleep(2)
                continue

            cleaned = sanitize_final_script(
                raw_text
            )

            print(
                f"CLEANED SCRIPT LENGTH: "
                f"{len(cleaned)}"
            )

            if len(cleaned) > TARGET_MAX_CHARS:
                cleaned = trim_to_target(
                    cleaned,
                    TARGET_MAX_CHARS,
                )

                cleaned = sanitize_final_script(
                    cleaned
                )

                print(
                    f"TRIMMED SCRIPT LENGTH: "
                    f"{len(cleaned)}"
                )

            valid, reason = validate_script(
                cleaned
            )

            if valid:
                print(
                    "SCRIPT VALIDATION: PASSED"
                )

                print(
                    f"FINAL SCRIPT LENGTH: "
                    f"{len(cleaned)}"
                )

                return cleaned

            last_error = reason

            print(
                "SCRIPT VALIDATION FAILED: "
                f"{reason}"
            )

        except Exception as exc:
            last_error = str(exc)

            print(
                "SCRIPT GENERATION ERROR: "
                f"{last_error}"
            )

        time.sleep(2)

    raise RuntimeError(
        "Script generation failed after "
        f"{MAX_ATTEMPTS} attempts: "
        f"{last_error}"
    )


def save_script(topic_id, script_text):
    SCRIPTS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    topic_id = str(
        topic_id
    ).zfill(3)

    path = (
        SCRIPTS_DIR
        / f"{topic_id}.txt"
    )

    with path.open(
        "w",
        encoding="utf-8",
    ) as file:
        file.write(
            script_text.strip()
        )

    print(
        f"SCRIPT SAVED: {path}"
    )

    return path


if __name__ == "__main__":
    print(
        "script.py is a module and should be "
        "called through build_pipeline.py"
    )
