name: Video Generator

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        run: pip install requests

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Build Visual Video
        run: python src/video.py

      - name: Save Video
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add videos/ visuals/
          git diff --cached --quiet || git commit -m "Create visual video"
          git push
